kind: Deployment
apiVersion: apps/v1
metadata:
  name: ping2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ping2
        deploymentconfig: ping2
    spec:
      containers:
        - name: httpd1
          image: quay.io/kcalliga/ping-container
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  paused: false
